"""RAG 模块测试：离线校验解析/切分，联网校验入库/检索。

运行：cd back && uv run python src/test_rag.py
前置：已复制 .env.example 为 .env 并填写 DASHSCOPE_API_KEY（联网部分必需）。
测试文档写入 knowledge_docs/（settings.knowledge_docs_dir），可重复运行。
"""

import sys
from pathlib import Path

import pymupdf

from config import settings
from rag import RagService, load_directory, split_documents

# Windows 控制台默认 GBK 会乱码，统一强制 UTF-8 输出（PyCharm / Windows Terminal 均适用）
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

PRODUCT_TXT = """DataPilot 产品介绍

DataPilot 是一款基于 LangChain Agent 与 RAG 的智能数据分析助手，面向单机单用户场景，
无需登录即可使用。

核心功能一：知识库问答。用户可以上传 PDF、TXT、Markdown 等文档，系统会解析文本、
按固定长度切分、调用向量模型生成嵌入，并存入本地的 Chroma 向量库。
提问时 Agent 会检索最相关的文档片段作为上下文，并在回答中给出来源引用，便于核对原文。

核心功能二：数据分析。用户可以上传 CSV 或 Excel 文件，Agent 会调用数据分析工具完成
统计、筛选与聚合，并把结果整理成 ECharts 图表配置返回给前端渲染，用户无需编写任何代码。

核心功能三：流式对话。后端通过 SSE 推送事件流，包括正文增量、工具调用状态、引用来源
与图表数据；前端实时渲染 Markdown 与代码高亮，打字机效果流畅自然，长回答也会逐字显示。

技术架构方面，后端使用 Python 3.13 与 FastAPI，Agent 由 langchain 1.x 的 create_agent
构建；向量库使用 Chroma 本地持久化；文档解析使用 pypdfium2 直接实现，不依赖任何
已归档的社区加载器包。前端使用 Vue 3 与 Element Plus，通过 fetch 读取 SSE 流。

使用流程非常简单：第一步，在知识库页面上传文档并等待入库完成；第二步，在对话页面
选择模型并提问；第三步，查看回答中的引用来源与图表卡片，并可按需继续追问。

常见问题：如果检索结果不理想，可以调整文本切分参数或更换向量模型后重建索引；
如果回答缺少引用，请确认提问与已入库文档的主题相关。更多说明见常见问题文档与技术说明 PDF。

设置页提供模型切换能力，可选模型包括 qwen3.7-plus、deepseek-v3 与 glm-5。
向量化模型默认使用 text-embedding-v3，向量数据持久化保存在 chroma_db 目录中。
"""

FAQ_MD = """# DataPilot 常见问题

## 知识库文档支持哪些格式？

目前支持 PDF、TXT 与 Markdown 三类文档。PDF 由 pypdfium2 逐页解析，每一页会记录页码；
TXT 与 Markdown 直接读取全文。

## 文本如何切分？

使用 langchain-text-splitters 的 RecursiveCharacterTextSplitter，默认参数为
chunk_size=700、chunk_overlap=100：每个片段最多 700 个字符，相邻片段重叠 100 个字符，
保证上下文连续。

## 向量库存储在哪里？

向量由阿里云百炼的 text-embedding-v3 模型生成，持久化保存到 back/chroma_db 目录，
重启服务后数据不会丢失。

## 回答中的引用来源如何生成？

检索返回的每个片段都带有 metadata，包括源文件路径与页码，Agent 据此生成引用来源卡片，
前端展示为可读的来源列表。

## 如何在设置页切换模型？

调用后端的 get_model 函数并传入模型名称即可，可选模型由 AVAILABLE_MODELS 环境变量控制。
"""

BUSINESS_MD = """# DataPilot 年度经营数据（示例）

## 销售与退货

2025 年全年销售额 1,200,000 元，产品退货率 4.5%，全年退货处理成本约 54,000 元。
退货处理成本与退货率成正比：退货率每降低 1 个百分点，退货处理成本约下降 12,000 元。

## 成本结构

运营成本中，物流仓储占 35%，退货处理占 5%，客服人力占 12%，其余为其他支出。
2026 年经营目标：将产品退货率控制在 2.5% 以内，销售额不低于 1,200,000 元。
"""

TECH_PDF_PAGES = [
    """DataPilot Technical Note 1: RAG Pipeline

The retrieval pipeline consists of four stages: parsing, splitting, embedding and
storage. Parsing is implemented directly with pypdfium2 for PDF files; text and
markdown files are read as plain text.

Splitting uses the RecursiveCharacterTextSplitter with a chunk size of 700
characters and an overlap of 100 characters, which keeps neighboring chunks
connected.

Embeddings are generated by the text-embedding-v3 model through the OpenAI
compatible endpoint. Vectors are stored in a local Chroma database that persists
on disk under the chroma_db directory, so the index survives process restarts.
""",
    """DataPilot Technical Note 2: Streaming Architecture

The backend exposes a single Server-Sent Events endpoint for chat streaming. The
agent emits events through astream_events, and the server filters them into a
small stable protocol: meta, token, reasoning, tool_start, tool_end, sources,
chart, error and done.

Raw events are never forwarded to the browser. The frontend consumes the stream
with fetch and ReadableStream because the native EventSource API cannot issue
POST requests. Rendered answers support Markdown and syntax highlighting.
""",
]


def _write_pdf(path: Path, pages: list[str]) -> None:
    """用 pymupdf 生成多页英文 PDF（避免中文字体嵌入问题）。"""
    document = pymupdf.open()
    for text in pages:
        page = document.new_page()
        leftover = page.insert_textbox(pymupdf.Rect(50, 50, 550, 780), text, fontsize=11)
        if leftover < 0:
            raise SystemExit(f"[FAIL] 测试 PDF 文本超出页面：{path.name}")
    document.save(str(path))
    document.close()


def create_test_docs() -> tuple[Path, Path, Path, Path]:
    """写入 4 个测试文档（txt / md / pdf / 经营数据 md），返回各自的路径。"""
    docs_dir = settings.knowledge_docs_dir
    docs_dir.mkdir(parents=True, exist_ok=True)

    txt_path = docs_dir / "01-产品介绍.txt"
    txt_path.write_text(PRODUCT_TXT, encoding="utf-8")

    md_path = docs_dir / "02-常见问题.md"
    md_path.write_text(FAQ_MD, encoding="utf-8")

    pdf_path = docs_dir / "03-tech-note.pdf"
    _write_pdf(pdf_path, TECH_PDF_PAGES)

    data_path = docs_dir / "04-经营数据.md"
    data_path.write_text(BUSINESS_MD, encoding="utf-8")

    return txt_path, md_path, pdf_path, data_path


def _offline_check(pdf_path: Path) -> None:
    """离线验证：目录批量解析 + 切分（不访问网络）。"""
    documents = load_directory()
    print(f"[OK] 批量解析：{len(documents)} 个 Document")
    for item in documents:
        name = Path(item.metadata["source"]).name
        page = f" 第 {item.metadata['page']} 页" if "page" in item.metadata else ""
        print(f"     - {name}{page}（{len(item.page_content)} 字符）")

    pdf_pages = [
        d for d in documents if Path(d.metadata["source"]).name == pdf_path.name
    ]
    if len(pdf_pages) != len(TECH_PDF_PAGES):
        raise SystemExit(
            f"[FAIL] PDF 应按页生成 {len(TECH_PDF_PAGES)} 个 Document，实际 {len(pdf_pages)} 个"
        )

    chunks = split_documents(documents)
    if not chunks:
        raise SystemExit("[FAIL] 切分结果为空")
    oversize = [c for c in chunks if len(c.page_content) > settings.chunk_size]
    if oversize:
        raise SystemExit(f"[FAIL] 存在超过 chunk_size 的片段：{len(oversize)} 个")
    print(
        f"[OK] 切分：{len(documents)} 个文档 → {len(chunks)} 个片段"
        f"（chunk_size={settings.chunk_size}, overlap={settings.chunk_overlap}）"
    )

    sample = chunks[0]
    preview = sample.page_content[:50].replace("\n", " ")
    print(f"     - 首个片段：{Path(sample.metadata['source']).name} | {preview}…")


def _online_check(paths: tuple[Path, ...]) -> None:
    """联网验证：入库 + 检索（需要已配置 DASHSCOPE_API_KEY）。"""
    service = RagService()
    service.clear()  # 幂等：重复运行不产生重复向量

    count = service.add_documents(list(paths))
    print(
        f"\n[OK] 入库：{len(paths)} 个文档 → {count} 个片段"
        f"（collection={service.collection_name}, 目录={service.persist_directory}）"
    )

    queries = [
        "DataPilot 支持哪些文档格式？",
        "文本切分的默认参数是多少？",
        "How does the frontend consume the stream?",
    ]
    for query in queries:
        results = service.search(query, k=3)
        if not results:
            raise SystemExit(f"[FAIL] 查询无结果：{query}")
        print(f"\n[检索] {query}")
        for rank, item in enumerate(results, start=1):
            name = Path(item.metadata["source"]).name
            page = f"（第 {item.metadata['page']} 页）" if "page" in item.metadata else ""
            snippet = item.page_content[:60].replace("\n", " ")
            print(f"  {rank}. {name}{page} {snippet}…")


def main() -> None:
    paths = create_test_docs()
    _offline_check(paths[2])

    if not settings.dashscope_api_key:
        print("\n[SKIP] 未配置 DASHSCOPE_API_KEY：跳过联网部分（入库 / 检索）。")
        print("       请在 back/.env 填写 Key 后重新运行，完成完整验证。")
        return

    try:
        _online_check(paths)
    except SystemExit:
        raise
    except Exception as exc:  # 汇总报错并以非零码退出（重新抛出，BLE001 豁免）
        raise SystemExit(f"[FAIL] 联网部分失败：{type(exc).__name__}: {exc}") from exc

    print("\n[OK] 全部验证通过")


if __name__ == "__main__":
    main()
